Repository koalalu007/ShoppingCartApp-, pull requests merged in 2023-10, with the labels that each got.

#4 added category page
  src/pages/Category.js
Labels: enhancement, hacktober, hacktoberfest-accepted, hacktoberfest

#5 added check out function
  src/pages/Checkout.js
  src/pages/Home.js
Labels: enhancement, help wanted, good first issue, hacktober, hacktoberfest-accepted, hacktoberfest

#7 Improve UI
  src/pages/Category.js
Labels: enhancement, good first issue, hacktober, hacktoberfest-accepted, hacktoberfest

#8 improve UI of Home.js
  src/db/categories.json
  src/db/products.json
  src/pages/Home.css
  src/pages/Home.js
Labels: enhancement, good first issue, hacktober, hacktoberfest-accepted, hacktoberfest
